# 02 — NumPy Fundamentals for Machine Learning

## Purpose
This notebook revises **NumPy concepts required for Machine Learning**.

Focus:
- Numerical arrays
- Vectorized operations
- Indexing and broadcasting
- Basic statistics and transformations

Out of scope:
- Linear algebra proofs
- Eigenvalues, SVD (covered later when needed)


In [2]:
import numpy as np

## Why NumPy?

NumPy is used because:
- It is **fast** (C-backed, contiguous memory)
- It supports **vectorized computation**
- Most ML libraries are built on top of it


In [4]:
# From Python lists
a = np.array([1, 2, 3, 4])

# Zeros and ones
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))

# Ranges
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

a, zeros, ones, arange, linspace


(array([1, 2, 3, 4]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

# linspace

In [ ]:
# linspace and Normalization
x = np.array([10, 20, 50, 80])
x_min, x_max = x.min(), x.max()

x_norm = (x - x_min) / (x_max - x_min)
grid = np.linspace(0, 1, len(x))

print("Normalized data:", x_norm)
print("Reference grid:", grid)

# Interpretation
# x_norm tells you where each value lies in the [0, 1] interval
# linspace defines the ideal evenly spaced reference positions

# This is exactly how:
# feature scaling
# histogram binning
# quantization

Normalized data: [0.         0.14285714 0.57142857 1.        ]
Reference grid: [0.         0.33333333 0.66666667 1.        ]


In [6]:
# linspace and Interpolation
# Interpolation estimates values between known data points.
# linspace provides the query locations where interpolation happens.

# Known samples
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])  # y = x^2

# Create dense query points
x_new = np.linspace(x.min(), x.max(), 20)

# Linear interpolation
y_new = np.interp(x_new, x, y)


## Shape, Dimensions, and dtype

Understanding array shape and data type is critical for:
- Model input expectations
- Broadcasting
- Debugging shape mismatch errors


In [7]:
# Create a random feature matrix
X = np.random.randn(100, 3)

# Inspect properties
X.shape, X.ndim, X.dtype


((100, 3), 2, dtype('float64'))

 # Reshaping
 - reshape() — the main tool
 - The total number of elements must remain the same

In [ ]:
sample = np.array([1,2,3,4,5,6])
s_reshaped = sample.reshape(2,3)
print(s_reshaped)

[[1 2 3]
 [4 5 6]]


In [23]:
# Using -1 (automatic dimension inference)
sample.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
sample.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

- Reshaping does NOT change memory (usually)

In [27]:
y = sample.reshape(2, 3)
# NumPy does not move or copy the data in memory in most cases.
"""
The same block of memory is reused
Only the metadata changes:
- shape
- strides 
"""

'\nThe same block of memory is reused\nOnly the metadata changes:\n- shape\n- strides \n'

## flatten
- flatten() converts a multi-dimensional array into a one-dimensional array by copying all elements into a new contiguous array.

In [29]:

xs = np.array([[1, 2, 3],
              [4, 5, 6]])

ys = xs.flatten()
ys

array([1, 2, 3, 4, 5, 6])

# Ravel
- ravel() converts an array into a one-dimensional array by flattening it when possible without copying data.

In [34]:
xs = np.array([[1, 2, 3],
              [4, 5, 6]])

ys = xs.ravel()

"""
flatten() → always makes a copy
ravel() → returns a view if possible, otherwise a copy
"""
ys

array([1, 2, 3, 4, 5, 6])

## Indexing and Slicing

Indexing is used to:
- Select rows (samples)
- Select columns (features)
- Extract submatrices

This is fundamental to ML data handling.


In [8]:
# Assume X from previous block
X.shape


(100, 3)

In [9]:
# First row (one sample)
X[0]


array([-0.2454044 , -0.77550811,  0.66039227])

In [10]:
# First feature (all rows)
X[:, 0]


array([-0.2454044 ,  0.88409466, -0.68588986,  3.09554424, -1.1408018 ,
       -0.44933001, -2.10809805, -0.19921498,  1.89015878, -1.76185886,
       -0.1966228 , -1.47074942, -1.80928425, -0.9325613 ,  2.2251952 ,
       -0.20453385,  0.36769399, -0.17000109, -0.01168072,  0.03523062,
       -0.70100355,  1.28300796,  1.29118274,  0.7454543 , -0.10563265,
       -0.58556484,  0.48221269, -1.09435784, -1.06851005, -0.98624717,
        0.24500807,  0.02842014,  3.03961618,  0.37258317, -0.94618319,
       -0.68712726, -1.12935182,  0.96788631,  1.48393611,  0.80019437,
        0.70359525,  0.4516005 , -1.22992422, -1.39033685,  0.23000156,
       -0.63378634, -0.2291123 ,  1.8172813 ,  0.08008125, -0.78533409,
        0.56037309, -0.5678604 ,  0.54645627, -1.17243036,  1.18998637,
        0.92668574, -0.5157828 ,  1.80778053, -0.65947391,  0.97867446,
        0.29712853, -0.04485252,  2.02271461, -0.21958567, -1.59612635,
        0.4056688 , -0.77652789, -0.18913035,  0.88204661,  0.46

In [11]:
# First 5 samples, first 2 features
X[:5, :2]


array([[-0.2454044 , -0.77550811],
       [ 0.88409466,  0.97782995],
       [-0.68588986,  0.60566628],
       [ 3.09554424,  0.10654455],
       [-1.1408018 ,  1.66307318]])

## Boolean Masking

Boolean masking allows selecting rows or values
based on conditions.

This is heavily used during data cleaning and preprocessing.


In [ ]:
# Condition on the first feature
mask = X[:, 0] > 0

mask[:10]
# mask is a Boolean array
# Same length as number of rows in X

array([False,  True, False,  True, False, False, False, False,  True,
       False])

In [13]:
# Select rows where first feature > 0
X_positive = X[mask]

X_positive.shape


(47, 3)

In [15]:
# Multiple conditions
mask_multi = (X[:, 0] > 0) & (X[:, 1] < 0)

X_filtered = X[mask_multi]

X_filtered.shape
# It selects all rows form X where the first feature is positive and the
# second feature is negative

(23, 3)

## Broadcasting

Broadcasting allows NumPy to perform operations on arrays
with different shapes by automatically expanding dimensions
when it is mathematically valid.

This is heavily used in:
- Feature scaling
- Normalization
- Centering data


In [16]:
# Mean and standard deviation per feature (column-wise)
mean = X.mean(axis=0)
std = X.std(axis=0)

mean, std


(array([0.07982872, 0.05850173, 0.02601752]),
 array([1.09298727, 1.03516765, 0.95606839]))

In [19]:
# Standardization using broadcasting
X_standardized = (X - mean) / std

X_standardized[:3]
# It standardizes each feature (column) of X so that 
# every feature has mean 0 and standard deviation 1
"""
from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit_transform(X)
"""

'\nfrom sklearn.preprocessing import StandardScaler\nX_scaled = StandardScaler().fit_transform(X)\n'

In [18]:
# After standardization:
X_standardized.mean(axis=0), X_standardized.std(axis=0)


(array([ 2.33146835e-17, -3.99680289e-17,  2.88657986e-17]),
 array([1., 1., 1.]))

## Aggregations and `axis`

`axis` tells NumPy **which direction to collapse**.

Rule of thumb:
- `axis=0` → column-wise (down the rows)
- `axis=1` → row-wise (across columns)


In [ ]:
# Column-wise mean (per feature)
X.mean(axis=0)


array([0.07982872, 0.05850173, 0.02601752])

In [21]:
# Row-wise mean (per sample)
X.mean(axis=1)[:5]


array([-0.12017342,  0.62199099,  0.01800452,  1.47245707,  0.10734266])

- Aggregation means reducing multiple values into a single summary value.

In [36]:
# aggregation over axis
x = np.array([
    [1,2,3],
    [4,5,6]])

np.sum(x, axis=0)

array([5, 7, 9])

In [37]:
np.sum(x, axis=1)

array([ 6, 15])

- Aggregation reduces dimensionality

In [38]:
x.shape               # (2, 3)
np.sum(x, axis=0).shape  # (3,)
np.sum(x, axis=1).shape  # (2,)
np.sum(x).shape          # ()


()

-  keepdims=True (critical for broadcasting)

In [40]:
np.sum(x, axis=1, keepdims=True)
# Keeps dimensions for later broadcasting

array([[ 6],
       [15]])

In [42]:
#  Multiple axes aggregation
x = np.random.rand(2, 3, 4)

np.mean(x, axis=(1, 2))
x

array([[[0.7444738 , 0.01738042, 0.18532307, 0.00568594],
        [0.59030414, 0.95039692, 0.93302949, 0.771544  ],
        [0.30676094, 0.54416894, 0.76217907, 0.51051154]],

       [[0.77582945, 0.78425267, 0.3120077 , 0.2928929 ],
        [0.50496884, 0.14943449, 0.80604818, 0.12060533],
        [0.10154448, 0.04746301, 0.4099199 , 0.54423705]]])

In [43]:
np.mean(x)        # NaNs propagate
np.nanmean(x)     # Ignores NaNs


np.float64(0.4654567615970506)

In [ ]:
x = np.array([True, False, True])

np.any(x)   # True 
np.all(x)   # False



np.False_

# Dot product
- Give weighted sum of features

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)
# or
a @ b
print(a@b)

32


- The dot product of two vectors is the sum of pairwise component multiplications, equal geometrically to the product of their magnitudes and the cosine of the angle between them.

-  np.dot() — legacy, overloaded behavior


In [48]:
np.dot([1,2,3],[4,5,6])

np.int64(32)

- np.matmul() — clean matrix multiplication
- @ operator — recommended syntax

- @ = np.matmul()
- np.dot() != np.matmul() -> only the same in some cases

In [3]:
# When all three give the same result
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a @ b
np.matmul(a, b)
np.dot(a, b)


np.int64(32)

In [ ]:
# When np.dot() behaves differently 
# Higher dimensional arrays 
A = np.random.rand(10, 2, 3)
B = np.random.rand(10, 3, 4)
A @ B

array([[[0.98000561, 0.45434116, 0.56199753, 0.60142108],
        [1.58197094, 0.37519788, 0.80972034, 1.365909  ]],

       [[0.97992253, 0.86681537, 0.36602067, 0.70750017],
        [0.47771469, 0.45443947, 0.16384168, 0.26658795]],

       [[0.08244153, 0.08244517, 0.06305428, 0.10379697],
        [0.79161585, 0.72771288, 0.40922704, 1.05396308]],

       [[0.48506802, 0.1515227 , 0.34912014, 0.39181376],
        [1.00177187, 0.50418336, 0.66748826, 0.55043876]],

       [[0.88893567, 0.69413107, 1.2567465 , 0.98541585],
        [0.43770533, 0.44365274, 0.73122687, 0.50264311]],

       [[1.12621571, 0.89299795, 1.15339599, 1.20647355],
        [0.3357204 , 0.25171852, 0.38008563, 0.36529894]],

       [[0.72759705, 0.68366902, 0.32517328, 0.95497124],
        [1.04920017, 0.98273369, 0.59782413, 1.01327104]],

       [[0.41049814, 0.02521368, 0.16760025, 0.30183677],
        [0.71590315, 0.26760434, 0.4918015 , 0.35229039]],

       [[0.71584496, 1.6812527 , 1.34513626, 1.53329274]

In [5]:
np.dot(A,B)

array([[[[0.98000561, 0.45434116, 0.56199753, 0.60142108],
         [0.69861616, 0.62798404, 0.25355107, 0.50132286],
         [0.65804581, 0.4592512 , 0.47235355, 0.64316437],
         [0.76326197, 0.52141104, 0.72929221, 0.47154208],
         [0.681444  , 0.48554888, 0.86702285, 0.76118628],
         [0.58136491, 0.3621879 , 0.67725806, 0.61118382],
         [0.74755664, 0.66056948, 0.46435139, 0.62457175],
         [0.59592689, 0.15080074, 0.37969269, 0.41891809],
         [0.26713067, 0.86398648, 0.68646379, 0.74607555],
         [0.64007047, 0.53337384, 0.59921878, 0.30311602]],

        [[1.58197094, 0.37519788, 0.80972034, 1.365909  ],
         [1.30324199, 1.09094069, 0.51891271, 1.06406007],
         [1.04543427, 0.65707884, 0.99278475, 0.79501463],
         [1.37510148, 0.61455856, 1.10899697, 1.01745959],
         [1.02715208, 0.67976855, 1.50588344, 1.06005295],
         [1.04056853, 0.81251262, 1.30227262, 1.18181421],
         [1.36420926, 1.23819966, 0.92630383, 0.907263

- The @ operator is exactly equivalent to np.matmul(), while np.dot() only matches them for simple 1D or 2D cases and behaves differently for higher-dimensional arrays.

- Use @ → always
- Use matmul() → if you need function form
- Use dot() → only when reading old code


# simple normalization using numpy


In [3]:
import numpy as np 

x = np.array([10,20,30,40])

x_min = x.min()
x_max = x.max()

x_norm = (x-x_min) / (x_max-x_min)
print(x_norm)

[0.         0.33333333 0.66666667 1.        ]


In [10]:
# normalizing a 2d array

x= np.array([[1,10],
             [2,20],
             [3,30]])

x_min = x.min(axis=0)
x_max = x.max(axis=0)

x_norm = (x-x_min) / (x_max - x_min)
print(x_norm)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [11]:
# image style normalization 
image = np.array([0,128,255], dtype=np.float32)
image_norm = image / 255.0

print(image_norm)

[0.        0.5019608 1.       ]
